---                                                            
- hosts: web
  become: yes
  gather_facts: true
  tasks:

  - name: Копируем filebeat
    copy:
      src: /home/user/ansible/filebeat-7.17.11-amd64.deb
      dest: /home/user

  - name: Устанавливаем filebeat
    apt:
      deb: /home/user/filebeat-7.17.11-amd64.deb

  - name: Копируем конфиг filebeat
    copy:
      src: /home/user/ansible/filebeat.yml
      dest: /etc/filebeat/filebeat.yml

  - name: filebeat автозагрузка
    systemd:
      name: filebeat.service
      enabled: true

  - name: Перезапускаем службы
    systemd:
      name: filebeat.service
      state: started
